# Generated by Django 3.2.13 on 2022-05-17 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0004_alter_company_company_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='company_id',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='user_authentication.company'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_id',
            field=models.IntegerField(),
        ),
    ]
