# Generated by Django 3.2.13 on 2022-05-18 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0007_rename_company_id_branch_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='company',
            new_name='company_id',
        ),
    ]
